### PR TITLE
Add ServiceProvider and Publishable Config

### PR DESCRIPTION
**Pull request by mcordingley**
PR sets up a more idiomatic way of configuring and resolving the base CipherSweet package as a service.

### CODE REVIEW

**Comment by paragonie-scott** [comment]
Hey just FYI this library was no where ready to be used by anyone for any reason. I open sourced it so I could test in an example app using Packagist. The understanding we have internally is that it may be scrapped and rewritten from the ground up entirely.

That said, I appreciate you taking the time to try to improve this toy implementation. I'll look over your changes when I have a chance.

**Comment by mcordingley** [comment]
Hi Scott.

I recognize this as not ready for production use. I do see a strong case for using it (when ready) in a project that I'm working on, so I'm ready to help push this to be production-ready. :smile:

**Comment by paragonie-scott** [comment]
Thanks! I've reviewed the changes and they look great.

**Comment by mcordingley** [comment]
More will be coming. :+1:

**Pull request merged**
